version: "3.8"

services:
  mysql:
    image: mysql:5.7.44
    container_name: mysql
    restart: on-failure
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - main-mysql-phpmyadmin
  phpmyadmin:
    image: phpmyadmin:apache
    container_name: phpmyadmin
    restart: on-failure
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    networks:
      - main-mysql-phpmyadmin
    depends_on:
      - mysql
networks:
  main-mysql-phpmyadmin:
